FROM python:3.8
RUN apt-get update \
    && apt-get install -y --no-install-recommends apt-utils \
    && apt-get install -y software-properties-common \
    && apt-add-repository --yes --update ppa:ansible/ansible \
    && apt-get install -y ansible

# Install tools required for linting
RUN apt-get install -y yamllint \
    && pip install ansible-lint \
    && pip install ansible-review

# Set up entrypoint
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
